// Auto-generated by scripts/update-after-deploy.mjs — do not edit by hand.
import type { ForumAddresses } from "./types.js";

export const ARC_TESTNET_DEPLOYMENT: ForumAddresses = {
  registry: "0x730825299821d411146c503915553e37ebdc750c",
  config: "0xf37b1eb28d9af1b259cad3d71a14e76ca8ae0d26",
  trackRecord: "0xaace70a50573cb077f65d601cd19103afc4aef9d",
  feeDistributor: "0x0574257629e8221d560cf4aace0f3cd7226be2a0",
  trackRecordV2: "0x8f1c8fbf569146f32ddfb5b817bf2bd213840a66",
  agentPool: "0x13855be80b6122187c0bcba007946f9fbaae3fae",
  slashBond: "0xe6c8c31477a1d88fbdad6e7b4fc83ab8e6e34939",
  riskKernel: "0x0af356f280af1d8b7a43f0746c581614feec4055",
  covenantVault: "0x80384963c0c93414ff16e018c6618a64bc94df6d",
};
