# Auto-generated by scripts/update-after-deploy.mjs — do not edit by hand.
from .client import ForumAddresses

ARC_TESTNET_DEPLOYMENT = ForumAddresses(
    registry="0x730825299821d411146c503915553e37ebdc750c",
    config="0xf37b1eb28d9af1b259cad3d71a14e76ca8ae0d26",
    track_record="0xaace70a50573cb077f65d601cd19103afc4aef9d",
    fee_distributor="0x0574257629e8221d560cf4aace0f3cd7226be2a0",
)
